src-git-full openstick https://github.com/lkiuyu/openstick-feeds.git^7476bcac6d9fa8ae1b69fe471799a30e56bbf584
src-git packages https://github.com/immortalwrt/packages.git^1fb5b6dcfa9420e5acf6ecf1fdda0c37b1d1bc23
src-git luci https://github.com/immortalwrt/luci.git^6ce0e2ad267d2261f02280cb1ee785cc279913d4
